import Head from 'next/head'
import Grid1 from '../components/grid1'

export default function Home() {
  return (
  <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
      <div className="grids">
       <Grid1/>
        <Grid1/>
        <Grid1/>
      </div>
      <div className="grids">
       <Grid1/>
        <Grid1/>
        <Grid1/>
      </div>
      <div className="grids">
       <Grid1/>
        <Grid1/>
        <Grid1/>
      </div>
  </div>
       
  </div>
  )
}
